#pragma once
#include "Definitions.h"
#include "GUI.h"
#include "MultiplayerGameMenu.h"
void mainmenu();
void options();
void Renderoptions();
void GUIoptions();
void worldmenu();
void createworldmenu();
